set_option – FiNeR
set_option Subroutine
Source File
private pure subroutine set_option(self, val)
Arguments
Type Intent Optional Attributes Name
class(option), intent(inout) :: self
Option data.
class(*), intent(in) :: val
Value.
Description
Set option data value (scalar).
Calls
Source Code
  pure subroutine set_option(self, val)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Set option data value (scalar).
  !---------------------------------------------------------------------------------------------------------------------------------
  class(option), intent(inout) :: self !< Option data.
  class(*),      intent(in)    :: val  !< Value.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  select type(val)
#ifdef r16p
  type is(real(R16P))
    self%ovals = val
#endif
  type is(real(R8P))
    self%ovals = val
  type is(real(R4P))
    self%ovals = val
  type is(integer(I8P))
    self%ovals = val
  type is(integer(I4P))
    self%ovals = val
  type is(integer(I2P))
    self%ovals = val
  type is(integer(I1P))
    self%ovals = val
  type is(logical)
    self%ovals = trim(str(n=val))
  type is(character(*))
    self%ovals = val
  endselect
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine set_option
Call graph
set_option calls str
str calls str_a_i2p, str_i4p, str_a_r4p, strf_i1p, str_bol, strf_r8p, str_r8p, strf_i8p, str_a_i4p, str_i2p, str_i8p, str_a_r8p, strf_r4p, str_i1p, strf_i2p, strf_i4p, str_a_i8p, str_r4p, str_a_i1p
str_a_i2p calls str_i2p
str_a_r4p calls str_r4p
str_a_i4p calls str_i4p
str_a_r8p calls str_r8p
str_a_i8p calls str_i8p
str_a_i1p calls str_i1p