str_I1P – FiNeR
str_I1P Function
Source File
private elemental function str_I1P(n, no_sign) result(str)
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: n
Integer to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
Return Value character(len=DI1P)
Returned string containing input number plus padding zeros.
Description
Convert integer to string.
Called By
Source Code
  elemental function str_I1P(n, no_sign) result(str)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Convert integer to string.
  !---------------------------------------------------------------------------------------------------------------------------------
  integer(I1P), intent(in)           :: n       !< Integer to be converted.
  logical,      intent(in), optional :: no_sign !< Flag for leaving out the sign.
  character(DI1P)                    :: str     !< Returned string containing input number plus padding zeros.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  write(str, FI1P) n                ! Casting of n to string.
  str = adjustl(trim(str))          ! Removing white spaces.
  if (n>=0_I1P) str='+'//trim(str)  ! Prefixing plus if n>0.
  if (present(no_sign)) str=str(2:) ! Leaving out the sign.
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction str_I1P
Call graph
str_a_i1p calls str_i1p
str calls str_i1p, str_a_i1p
string_assign_real_r8p calls str
bctor_r16p calls str
string_assign_integer_i8p calls str
string_assign_integer_i4p calls str
set_a_option calls str
string_assign_real_r16p calls str
file_ini_autotest calls str
bctoi_i2p calls str
autotest calls str, file_ini_autotest
bctor_r4p calls str
string_assign_real_r4p calls str
string_assign_integer_i2p calls str
bctoi_i1p calls str
bctor_r8p calls str
bctoi_i8p calls str
string_assign_integer_i1p calls str
set_option calls str
bctoi_i4p calls str
bcton calls bctoi_i2p, bctor_r4p, bctoi_i1p, bctor_r8p, bctoi_i8p, bctoi_i4p