str_a_R8P – FiNeR
str_a_R8P Function
Source File
private pure function str_a_R8P(n, no_sign, delimiters) result(str)
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: n(:)
Real array to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
character(len=*), intent(in), optional :: delimiters(1:2)
Eventual delimiters of array values.
Return Value character(len=:), allocatable
Returned string containing input number.
Description
Convert real array to string.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
character(len=DR8P), public :: strn
String containing of element of input array number.
integer, public :: i
Counter.
Source Code
  pure function str_a_R8P(n, no_sign, delimiters) result(str)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Convert real array to string.
  !---------------------------------------------------------------------------------------------------------------------------------
  real(R8P),    intent(in)           :: n(:)            !< Real array to be converted.
  logical,      intent(in), optional :: no_sign         !< Flag for leaving out the sign.
  character(*), intent(in), optional :: delimiters(1:2) !< Eventual delimiters of array values.
  character(len=:), allocatable      :: str             !< Returned string containing input number.
  character(DR8P)                    :: strn            !< String containing of element of input array number.
  integer                            :: i               !< Counter.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  if (present(no_sign)) then
    str = ''
    do i=1,size(n)
      strn = str_R8P(no_sign=no_sign, n=n(i))
      str = str//','//trim(strn)
    enddo
  else
    str = ''
    do i=1,size(n)
      strn = str_R8P(n=n(i))
      str = str//','//trim(strn)
    enddo
  endif
  str = trim(str(2:))
  if (present(delimiters)) str = delimiters(1)//str//delimiters(2)
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction str_a_R8P
Call graph
str_a_r8p calls str_r8p
str calls str_a_r8p
bctor_r16p calls str
string_assign_integer_i4p calls str
string_assign_real_r4p calls str
string_assign_real_r8p calls str
set_a_option calls str
string_assign_real_r16p calls str
bctor_r8p calls str
bctoi_i4p calls str
bctor_r4p calls str
string_assign_integer_i2p calls str
string_assign_integer_i8p calls str
string_assign_integer_i1p calls str
bctoi_i8p calls str
autotest calls str
set_option calls str
bctoi_i1p calls str
bctoi_i2p calls str
bcton calls bctor_r8p, bctoi_i4p, bctor_r4p, bctoi_i8p, bctoi_i1p, bctoi_i2p