byte_size – FiNeR
byte_size Interface
Source File
public interface byte_size
Compute the number of bytes of a variable.
Calls
Called By
Module Procedures
private elemental function byte_size_I8P(i) result(bytes)
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: i
Integer variable whose number of bytes must be computed.
Return Value integer(kind=I1P)
Number of bytes of i.
Description
Compute the number of bytes of an integer variable.
private elemental function byte_size_I4P(i) result(bytes)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: i
Integer variable whose number of bytes must be computed.
Return Value integer(kind=I1P)
Number of bytes of i.
Description
Compute the number of bytes of an integer variable.
private elemental function byte_size_I2P(i) result(bytes)
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: i
Integer variable whose number of bytes must be computed.
Return Value integer(kind=I1P)
Number of bytes of i.
Description
Compute the number of bytes of an integer variable.
private elemental function byte_size_I1P(i) result(bytes)
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: i
Integer variable whose number of bytes must be computed.
Return Value integer(kind=I1P)
Number of bytes of i.
Description
Compute the number of bytes of an integer variable.
private elemental function byte_size_R8P(i) result(bytes)
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: i
Real variable whose number of bytes must be computed.
Return Value integer(kind=I1P)
Number of bytes of r.
Description
Compute the number of bytes of a real variable.
private elemental function byte_size_R4P(i) result(bytes)
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: i
Real variable whose number of bytes must be computed.
Return Value integer(kind=I1P)
Number of bytes of r.
Description
Compute the number of bytes of a real variable.
private elemental function byte_size_chr(i) result(bytes)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: i
Character variable whose number of bytes must be computed.
Return Value integer(kind=I4P)
Number of bytes of c.
Description
Compute the number of bytes of a character variable.
Call graph
byte_size calls byte_size_r8p, byte_size_i4p, byte_size_i2p, byte_size_i1p, byte_size_r4p, byte_size_i8p, byte_size_chr
b64_encode_string calls byte_size
b64_decode_string calls byte_size
b64_decode_string_a calls byte_size
b64_encode_string_a calls byte_size
b64_encode_up calls b64_encode_string, b64_encode_up_a, b64_encode_up
b64_encode calls b64_encode_string, b64_encode_string_a
autotest calls b64_encode, b64_decode
encode calls b64_encode
b64_decode_up calls b64_decode_string, b64_decode_up_a, b64_decode_up
b64_decode calls b64_decode_string, b64_decode_string_a
decode calls b64_decode
b64_decode_up_a calls b64_decode_string_a
b64_encode_up_a calls b64_encode_string_a