set_a_option – FiNeR
set_a_option Subroutine
Source File
private pure subroutine set_a_option(self, val, delimiter)
Arguments
Type Intent Optional Attributes Name
class(option), intent(inout) :: self
Option data.
class(*), intent(in) :: val(1:)
Value.
character(len=*), intent(in), optional :: delimiter
Delimiter used for separating values.
Description
Set option data value (array).
Calls
Variables
Type Visibility Attributes Name Initial
character(len=:), public, allocatable :: dlm
Dummy string for delimiter handling.
integer(kind=I4P), public :: v
Counter.
Source Code
  pure subroutine set_a_option(self, val, delimiter)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Set option data value (array).
  !---------------------------------------------------------------------------------------------------------------------------------
  class(option),          intent(inout) :: self      !< Option data.
  class(*),               intent(in)    :: val(1:)   !< Value.
  character(*), optional, intent(in)    :: delimiter !< Delimiter used for separating values.
  character(len=:), allocatable         :: dlm       !< Dummy string for delimiter handling.
  integer(I4P)                          :: v         !< Counter.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  dlm = ' ' ; if (present(delimiter)) dlm = delimiter
  self%ovals = ''
  select type(val)
#ifdef r16p
  type is(real(R16P))
    do v=1, size(val, dim=1)
      self%ovals = self%ovals//dlm//trim(str(n=val(v)))
    enddo
    self%ovals = self%ovals%strip()
#endif
  type is(real(R8P))
    do v=1, size(val, dim=1)
      self%ovals = self%ovals//dlm//trim(str(n=val(v)))
    enddo
    self%ovals = self%ovals%strip()
  type is(real(R4P))
    do v=1, size(val, dim=1)
      self%ovals = self%ovals//dlm//trim(str(n=val(v)))
    enddo
    self%ovals = self%ovals%strip()
  type is(integer(I8P))
    do v=1, size(val, dim=1)
      self%ovals = self%ovals//dlm//trim(str(n=val(v)))
    enddo
    self%ovals = self%ovals%strip()
  type is(integer(I4P))
    do v=1, size(val, dim=1)
      self%ovals = self%ovals//dlm//trim(str(n=val(v)))
    enddo
    self%ovals = self%ovals%strip()
  type is(integer(I2P))
    do v=1, size(val, dim=1)
      self%ovals = self%ovals//dlm//trim(str(n=val(v)))
    enddo
    self%ovals = self%ovals%strip()
  type is(integer(I1P))
    do v=1, size(val, dim=1)
      self%ovals = self%ovals//dlm//trim(str(n=val(v)))
    enddo
    self%ovals = self%ovals%strip()
  type is(logical)
    do v=1, size(val, dim=1)
      self%ovals = self%ovals//dlm//trim(str(n=val(v)))
    enddo
    self%ovals = self%ovals%strip()
  type is(character(*))
    do v=1, size(val, dim=1)
      self%ovals = self%ovals//dlm//trim(val(v))
    enddo
    self%ovals = self%ovals%strip()
  endselect
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine set_a_option
Call graph
set_a_option calls str
str calls strf_r4p, strf_i1p, str_a_r8p, str_a_i2p, str_a_i1p, strf_i8p, str_a_i8p, str_r4p, str_i2p, strf_i4p, strf_r8p, str_i1p, str_bol, str_a_i4p, str_r8p, str_a_r4p, str_i8p, strf_i2p, str_i4p
str_a_r8p calls str_r8p
str_a_i2p calls str_i2p
str_a_i1p calls str_i1p
str_a_i8p calls str_i8p
str_a_i4p calls str_i4p
str_a_r4p calls str_r4p