strf_I4P – FiNeR
strf_I4P Function
Source File
private elemental function strf_I4P(fm, n) result(str)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fm
Format different from the standard for the kind.
integer(kind=I4P), intent(in) :: n
Integer to be converted.
Return Value character(len=DI4P)
Returned string containing input number.
Description
Convert integer to string.
Called By
Source Code
  elemental function strf_I4P(fm, n) result(str)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Convert integer to string.
  !---------------------------------------------------------------------------------------------------------------------------------
  character(*), intent(in) :: fm  !< Format different from the standard for the kind.
  integer(I4P), intent(in) :: n   !< Integer to be converted.
  character(DI4P)          :: str !< Returned string containing input number.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  write(str, trim(fm)) n
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction strf_I4P
Call graph
str calls strf_i4p
autotest calls str
string_assign_integer_i2p calls str
string_assign_integer_i4p calls str
bctor_r4p calls str
string_assign_real_r4p calls str
set_option calls str
bctoi_i8p calls str
bctoi_i2p calls str
string_assign_integer_i1p calls str
bctoi_i1p calls str
string_assign_real_r16p calls str
bctor_r16p calls str
string_assign_real_r8p calls str
string_assign_integer_i8p calls str
set_a_option calls str
bctor_r8p calls str
bctoi_i4p calls str
bcton calls bctor_r4p, bctoi_i8p, bctoi_i2p, bctoi_i1p, bctor_r8p, bctoi_i4p