name: Test (alternative) Install Methods

on: push

jobs:
  install:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: INSTALL SCRIPT + cmake
      run: |
        wget $(curl -s https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest | grep 'browser_' | cut -d\" -f4 | grep -i install.sh)
        chmod +x install.sh
        ./install.sh --download wget --build cmake
        rm -rf *
